### ISSUE TITLE
Querying my own user data without going throught auth2

### ISSUE THREAD

**Issue by jiwidi** [spotipy-dev/spotipy#672]
Hi!

First, thanks for the hard work on the library, seems pretty cool.

I'm using the library and I would like to query my recent listened tracks. I know there is a method for that `current_user_recently_played` but it requires the spotipy client to have a current user, for that you have to go through a auth2 process (If I'm not mistaken). I would like to be able to query my own user recent songs without going through the manual authentication phase as I want to automate this in a script. If I could automate the authentication with a personal token that would work for me.

Is there a way to do that with this library? I thought I could probably generate an auth2 token from spotify and use it as seen in their example: https://developer.spotify.com/console/get-recently-played/?limit=&after=&before= but the tokens there expire in less than a day and I haven't seen any other way.

Best,
Jaime

**Comment by stephanebruckert** [comment]
You _have_ to go through the oauth process just once. Then re-running the script at any time will use the refresh_token to build a new token that will be valid for 1 hour.

**Comment by jiwidi** [comment]
> You _have_ to go through the oauth process just once. Then re-running the script at any time will use the refresh_token to build a new token that will be valid for 1 hour.

That token will only be valid for 1 hour? Is there a way to extend it?

**Comment by stephanebruckert** [comment]
It will automatically refresh so you won't have to worry about it

**Comment by jiwidi** [comment]
> It will automatically refresh so you won't have to worry about it

Sorry I didnt phrased it correctly. Is there any way to extend how long it will last so I dont have to refresh it every hour by running the script? I was thinking on running this script daily but will have to cut it down to hourly if the token can only last 1 hour without refresh

**Comment by stephanebruckert** [comment]
If the token expires, spotipy will automatically use the refresh token to retrieve a new token. And that refresh_token never expires! In your case running it daily will just work

**Comment by jiwidi** [comment]
Hi again,

How should I instantiate the spotipy client for it to use the refresh token? My token just expired and it didnt automatically ask for refresh token.

Script code:

```python
import spotipy
import json
import os
import time

token = os.environ['SPOTIFY_TOKEN']


sp = spotipy.Spotify(auth=token)
results = sp.current_user_recently_played()
results["date_run"] = time.time()
with open(".github/spotify_query_results.json", "w+") as f:
    json.dump(results,f)
```

The token I'm using there I got it from the following script:

```python
import sys
import spotipy
import spotipy.util as util

scope = 'user-read-recently-played'
username = 'xxx'
token = util.prompt_for_user_token(username, scope, redirect_uri="http://localhost:8888/callback/")

print(token)
```

Should I instantiate spotipy client differently in my script? Or what am I missing so the client refreshes the token by itself.

**Comment by Peter-Schorn** [comment]
Don't use `prompt_for_user_token`; it's been deprecated because it does not automatically refresh the access token. Instead, do this:

```python
from spotipy import Spotify, SpotifyOAuth, CacheFileHandler

username = "your username"
scope = "user-read-recently-played"
redirect_uri = "your redirect uri"

spotify = Spotify(
    auth_manager=SpotifyOAuth(
        redirect_uri=redirect_uri,
        scope=scope,
        cache_handler=CacheFileHandler(username=username)
    )
)

results = spotify.current_user_recently_played()

print(results)
```

**Comment by stephanebruckert** [comment]
Yes ⬆️ 

I also see you are passing the token through an environment variable and I guess you are doing that to pass the token from your local machine to the server? Depending on where your app will be deployed, you will have to adapt the code a bit:
 - use `open_browser=False` if you have access to a terminal on the server side, this way the login URL will be printed instead of opened, 
 - if the server doesn't give access to a terminal, you will have to run the code first on your local machine, and then make sure the server can access that token. You might need a [customized cache handler](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-can-i-store-tokens-in-a-database-rather-than-on-the-filesystem)

Where do you plan to deploy your code?

**Comment by jiwidi** [comment]
> Don't use `prompt_for_user_token`; it's been deprecated because it does not automatically refresh the access token. Instead, do this:
> 
> ```python
> from spotipy import Spotify, SpotifyOAuth, CacheFileHandler
> 
> username = "your username"
> scope = "user-read-recently-played"
> redirect_uri = "your redirect uri"
> 
> spotify = Spotify(
>     auth_manager=SpotifyOAuth(
>         redirect_uri=redirect_uri,
>         scope=scope,
>         cache_handler=CacheFileHandler(username=username)
>     )
> )
> 
> results = spotify.current_user_recently_played()
> 
> print(results)
> ```
> 
> The token info will be saved to a file and automatically refreshed when necessary.

I see, for what I have just tested if that file is missing it will ask for authentication again right? I'm planning to run this script with github actions so its going to be a spin up VM and state won't be maintained between runs (neither I want to save the file in the repo)

Is there any way to save the refresh token and pass it to the SpotifyOAuth every time? This way I can save the refreshtoken as a github repository secret and the main token will be refreshed every execution.

**Comment by jiwidi** [comment]
> Yes 
> 
> I also see you are passing the token through an environment variable and I guess you are doing that to pass the token from your local machine to the server? Depending on where your app will be deployed, you will have to adapt the code a bit:
> 
> * use `open_browser=False` [if you have access to a terminal](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-do-i-obtain-authorization-in-a-headlessbrowserless-environment) on the server side, this way the login URL will be printed instead of opened,
> * if the server doesn't give access to a terminal, you will have to run the code first on your local machine, and then make sure the server can access that token. You might need a [customized cache handler](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-can-i-store-tokens-in-a-database-rather-than-on-the-filesystem).
> 
> Where do you plan to deploy your code?

I plan to run it with github actions so saving into a common cache file shared between executions is a no go. Unless there is a way to pass the refresh token to SpotifyOAuth(then I can use github repo secrets to do so) instead from reading from a file I think  is hard.

The other idea is to save the whole file content as a secret and save it to file during script execution time.

**Comment by stephanebruckert** [comment]
The github action use case is an interesting one... because indeed the state is not saved between runs. I am not certain that using the same refresh_token as a GHA secret will work, I would bet that it is invalidated as soon as it is used.

Here is another suggestion... It's usually not something I would recommend for production code, but it looks perfect for the CI use case. There is a way to get a user token that is valid for 1 year (instead of 1 hour). It has to be manually retrieved from the cookies. Have a look at https://github.com/enriquegh/spotify-webplayer-token. You could just store it as a GHA secret and then pass it to spotipy as you initially did:

    token = os.environ['SPOTIFY_TOKEN']

    spotipy.Spotify(auth=token)

**Comment by jiwidi** [comment]
> The github action use case is an interesting one... because indeed the state is not saved between runs. I am not certain that using the same refresh_token as a GHA secret will work, I would bet that it is invalidated as soon as it is used.
> 
> Here is another suggestion... It's usually not something I would recommend for production code, but it looks perfect for the CI use case. There is a way to get a user token that is valid for 1 year (instead of 1 hour). It has to be manually retrieved from the cookies. Have a look at https://github.com/enriquegh/spotify-webplayer-token. You could just store it as a GHA secret and then pass it to spotipy as you initially did:
> 
> ```
> token = os.environ['SPOTIFY_TOKEN']
> 
> spotipy.Spotify(auth=token)
> ```

That is a good solution yeah, if I can't make the secrets work will probably go with that one. I think I could update the secret with a new refresh token if that is generated when one is used. Is the `.cache-username` file containing REFRESH_TOKEN updated with new refresh token when this one is used?

I was thinking how could the github action look and this is so far what I have

```
      # Create cache files for spotipy auth
      - name: Cache auth spotipy
        run: echo ${{ secrets.CACHE_JIWIDI }} > .github/.cache-jiwidi

      # Run our spotify query
      - name: Run spotify query
        run: python .github/queryspotify.py
        env:
          SPOTIPY_CLIENT_SECRET=: ${{ secrets.SPOTIPY_CLIENT_SECRET}}
          SPOTIPY_CLIENT_ID=: ${{ secrets.SPOTIPY_CLIENT_ID}}
          SPOTIPY_REDIRECT_URI=: ${{ secrets.SPOTIPY_REDIRECT_URI}}

      # UPDATE SECRET
      - name: Update Cache auth spotipy
        run: ##SOME CODE THAT READS .cache-jiwidi AND UPDATES CACHE_JIWIDI SECRET WITH THE CONTENT
```

**Comment by Peter-Schorn** [comment]
I don't think it's possible to update the value of a secret during/after the execution of a workflow. The github docs don't say anything about this.

**Comment by jiwidi** [comment]
> I don't think it's possible to update the value of a secret during/after the execution of a workflow. The github docs don't say anything about this.

With a quick Google search I found some actions that do it: https://github.com/hmanzur/actions-set-secret. Haven't gone too much detailed inside the code but I guess I could get the required code to do what I suggested.

**Comment by Peter-Schorn** [comment]
Well, then, this makes things much simpler. All you need to do is create a [custom cache handler](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-can-i-store-tokens-in-a-database-rather-than-on-the-filesystem) that retrieves and saves the token info to the secrets API.

```python
from spotipy import Spotify, SpotifyOAuth, CacheHandler
import json

class SecretsCacheHandler(CacheHandler):

    def save_token_to_cache(self, token_info):
        # `token_info` will be a python dict.
        token_string = json.dumps(token_info)
        # save the `token_string` to your secrets

    def get_cached_token(self):
        token_string = # retrieve the token info string from your secrets
        
        # convert the string back to a dict and return it
        token_info = json.loads(token_string)
        return token_info
```

**Comment by jiwidi** [comment]
> > With a quick Google search I found some actions that do it: https://github.com/hmanzur/actions-set-secret.
> 
> 
> 
> Well, then, this makes things much simpler. All you need to do is create a [custom cache handler](https://github.com/plamere/spotipy/blob/master/FAQ.md#how-can-i-store-tokens-in-a-database-rather-than-on-the-filesystem) that retrieves and saves the token info to the secrets API.
> 
> 
> 
> ```python
> 
> from spotipy import Spotify, SpotifyOAuth, CacheHandler
> 
> import json
> 
> 
> 
> class SecretsCacheHandler(CacheHandler):
> 
> 
> 
>     def save_token_to_cache(self, token_info):
> 
>         # `token_info` will be a python dict. convert it to a JSON string.
> 
>         token_string = json.dumps(token_info)
> 
>         # save the `token_string` to your secrets
> 
> 
> 
>     def get_cached_token(self):
> 
>         token_string = # retrieve the token info string from your secrets
> 
>         
> 
>         # convert the string back to a dict and return it
> 
>         token_info = json.loads(token_string)
> 
>         return token_info
> 
> ```
> 
> Then create your instance of `Spotify` using the cache handler:
> 
> ```python
> 
> scope = "user-read-recently-played"
> 
> spotify = Spotify(
> 
>     auth_manager=SpotifyOAuth(
> 
>         scope=scope,
> 
>         cache_handler=SecretsCacheHandler()
> 
>     )
> 
> )
> 
> ```

Such a clean solution! Will try implement it :)

**Comment by Peter-Schorn** [comment]
You'll have to use the [secrets API](https://docs.github.com/en/rest/reference/actions#secrets) directly because you need to call it from within your python script.

**Comment by stephanebruckert** [comment]
@Peter-Schorn great idea!

@jiwidi if you manage to do this, feel free to open a PR to add a GithubSecretsCacheHandler.

This is something we could even use for Github Actions in the current repo, as we are not currently running integration tests automatically.

**Comment by jiwidi** [comment]
> @Peter-Schorn great idea!
> 
> 
> 
> @jiwidi if you manage to do this, feel free to open a PR to add a GithubSecretsCacheHandler.
> 
> 
> 
> This is something we could even use for Github Actions in the current repo, as we are not currently running integration tests automatically.

Sure, will do!

**Comment by Peter-Schorn** [comment]
It looks like there is a python wrapper for the github API: https://github.com/PyGithub/PyGithub

**Comment by jiwidi** [comment]
@Peter-Schorn @stefanondisponibile 

I'm now working in the implementation and it can be done in different ways, with a PR in mind to add this secretCacheHandler, would you guys prefer to do the requests manually or use the github api?

Both have benefits, without the github API you don't add an extra requirement and without it your request is easier to become obsolete in the future as the API would presumably keep updating. 

I really don't mind which but since it will go for PR you probably have some preferences

**Comment by stephanebruckert** [comment]
Just use the library, that's what it's for!

**Comment by Peter-Schorn** [comment]
> would you guys prefer to do the requests manually or use the github api?

I don't know what this means. If you're updating the secrets programmatically, then surely you have to do this via the API one way or another, right?

**Comment by jiwidi** [comment]
I think I found a bug on their API because they list the `create_secret()` method and define it in the code but the callable is missing. Maybe the missed to include it in a init file or something, opened an issue on their repo https://github.com/PyGithub/PyGithub/issues/1923

Hopefully I missed something and is an easy fix :/

**Comment by Peter-Schorn** [comment]
It's not a bug; you're looking at an unreleased version of the repository. To install the latest commit from master:
```
pip uninstall PyGithub
pip install git+git://github.com/PyGithub/PyGithub@master
```

**Comment by jiwidi** [comment]
> It's not a bug; you're looking at an unreleased version of the repository. To install the latest commit from master:
> 
> ```
> pip uninstall PyGithub
> pip install git+git://github.com/PyGithub/PyGithub@master
> ```

I thought the documentation would only include changes from the latest released versions, mistake then!

**Comment by felix-hilden** [comment]
Just to give my two cents, I've used the same Spotify refresh token for API testing for essentially over a year now with daily runs. It truly does never expire! There's no limit on how many tokens can be requested, hence it's great utility for serialisation and databases. PKCE refresh tokens do expire though, so don't use *them*.

**Comment by jiwidi** [comment]
So I have a working script now:

```python
from spotipy import Spotify, SpotifyOAuth, CacheHandler
import time
import json
import os
from github import Github
import difflib

class SecretsCacheHandler(CacheHandler):
    def __init__(self, repository_name, github_access_token=None, github_access_token_secret_name=None, secret_cache_name="SPOTIPY_CACHE"):
        CacheHandler.__init__(self)
        #Create github api client from token or secret name containing token
        if(github_access_token!=None):
            self.github_client = Github(github_access_token)
        elif(github_access_token_secret_name!=None):
            self.github_client = Github(os.environ[github_access_token_secret_name])
        else:
            raise Exception("You must provide token or secret name containing your github access token in order to instantiate the cache handler")

        self.secret_cache_name = secret_cache_name
        self.repository = self.github_client.get_repo(repository_name)

    def save_token_to_cache(self, token_info):
        # `token_info` will be a python dict. convert it to a JSON string.
        token_string = json.dumps(token_info)
        # save the `token_string` to your secrets
        # self.repository.create_secret(secret_name=self.secret_cache_name,unencrypted_value=token_string)

    def get_cached_token(self):
        #Retrieve secret from enviorment
        token_string = os.environ[self.secret_cache_name]

        # Convert the string back to a dict and return it
        token_info = json.loads(token_string)

        return token_info


username = "jiwidi"
scope = "user-read-recently-played"

spotify = Spotify(
    auth_manager=SpotifyOAuth(
        scope=scope,
        cache_handler=SecretsCacheHandler(repository_name="jiwidi/jiwidi.github.io", github_access_token_secret_name="MAIN_TOKEN"),
    )
)

results = spotify.current_user_recently_played()
results["date_run"] = time.time()

with open(".github/spotify_query_results.json", "w+") as f:
    json.dump(results,f)
```

And the github action that triggers it:

```yaml

name: SPOTIFYQUERY

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  #Run every day at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up python libraries
        run: python -m pip install requests spotipy==2.18

      - name: Latest pytigt
        run: python -m pip install git+git://github.com/PyGithub/PyGithub@master

      # Run our spotify query with custom secretCacheHandler
      - name: Run spotify query
        run: python .github/queryspotify.py
        env:
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET}}
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID}}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI}}
          SPOTIPY_CACHE: "${{ secrets.SPOTIPY_CACHE}}"
          MAIN_TOKEN: '${{ secrets.MAIN_TOKEN}}'

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "A robot updating spotify query results. Beep beep boop"
          git push
```

Will do some more testing and open a PR if all is good.
